env:
  browser: true
  es2021: true
  amd: true
extends:
  - plugin:react/recommended
  - standard
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
  ecmaFeatures:
    jsx: true
    modules: true
plugins:
  - react
rules: {}
