env:
  browser: true
  es2021: true
  amd: true
extends:
  - plugin:react/recommended
  - standard
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
  ecmaFeatures:
    jsx: true
    modules: true
plugins:
  - react
rules: 
  react/prop-types:
    - 'off'
  react/react-in-jsx-scope:
    - 'off'
  prefer-promise-reject-errors:
    - 'off'
  multiline-ternary:
    - 'off'
